### ISSUE TITLE
Support multiple classes for Liminal

### ISSUE THREAD

**Issue by gilbert** [barneycarroll/cascading-components#25]
I use tailwind, so it's useful to add multiple classes like this:

```js
m(Liminal, {
  present: "transition duration-300",
  entry: "opacity-100",
  exit: "opacity-0",
}, ...)
```

However this throws the standard browser error:

```
InvalidCharacterError: The string contains invalid characters.
```

on a `dom.classList.add` line.

**Comment by barneycarroll** [comment]
Fixed in e0a4c74 - Liminal now additionally accepts arrays of classes. [In this example](https://flems.io/#0=N4IgtglgJlA2CmIBcA2AHAOhQGhAMwgQGdkBtUAOwEMxEkQMArE3AYwHsKAXeb5ECGAAO7AE5cABMAAygiNVgBfCXlHswEgDrgIXABajCAWjBVWe+fCNd27WEW2aKThJKgQiQ2FQCeEgLwqVPbwTk5Q7KwArrTcGABG7FA+GKzeRESyRFwYVDAAFNpCRgAs2thaIPEA5kZC8gDWRgDMAAyt2gCUYRRgGGDsUdz5EdGxOYnJFcBOEhIAbhDwAO5IEvmdAQB8EqSzcxJghVVRXDYUCbXxsFFWAKztGHrs8-CiSDVG17dGAOyPPAAHlwjMsLDwMHhOCDErAoBghD4jAAmBGA0oYNRDKDwKDlKT7A4SThpCCsBobGYUIlE9yebx+QIAQjpXl8hIOimwHK5HLm2gAKuxqtUEOUOZ1uc5qQdWQyJAAyBVaGVEo6ySAKaZ8g5CUTwIi8LhrPYgLiiKgUIi6CCcfHac2WohQ0Rge0gKBRC1cW0UFrtd3sIRmXRIgCMAZAFW0RFYwSsEY6IAAulKaQcqPFDdwTQ6LVaXW6o5UgyGuEik6mdXMjaIfGsY3GEEYk2n0xJ4IDdLmPV6qD7OH9I9GQLH4387toq6rOW300dtAijCh+lR0csjEQ+mB0VRTuxLqDwfBMYMKDioEZAbAMEQ9Hl2BuwPDPGYrOiylHqwcFwwgSDr0haETFxCAYgwf8vm8cl3QACXgWBYHYLo53bX8IM7EFqgtJEHlbSpYIgJkUO-SUdTImVp0UTooxADhhEIN5+HiTMENow0EFYAcrX4ZEwyQEpmiMMM0CQVoQEUVMQFgRoSCQcgQGoWh+EgfRDBvZhaK9WB+D0M4hCIJAAHojKGIQGmqVJ1CM1SDEIAABVFWgwEobN0OyNJYM0fCEOhR1YQwhC4CTsEoGg-K4KhCGWeR4U1VIMi00QdPoPSuAM4zTIoczLPoozIui2LWAyRyMGc5ojLpLh8qi2AYvPfp5ASrzy18-hsh8BAJOTRQgA):

```js
m(Liminal, {
  present: ["transition", "transform", "duration-300", "opacity-100", "scale-100"],
  absent: ["transition", "transform", "opacity-0"],
  entry: "scale-0",
  exit: ["duration-700", "scale-75"],
}, /*💥*/)
```

Your example shows a different understanding of how classes ought to be applied - which makes me wonder if the configuration interface needs tweaking:

1. Applies `absent` & `entry` in the immediate render frame
2. Forces a render, then immediately removes the above, and applies `present`
3. On removal trigger, removes the above, and applies `absent` & `exit`

Because the classes are designed as states arrived at and departed from, `present` is somewhat redundant. In my example I've spammed it with values for the sake of a 'complete' description of the liminal states in configuration - where perhaps the distinction of an `exit` `duration-700` is better controlled - but in practice all these classes could (perhaps ought to?) be applied directly to the childs hyperscript expression.

**Comment by gilbert** [comment]
Awesome, it works! Do you think you could do a string `.split()` internally so I can write my css strings with spaces? I already have to think about `.x.y.z` vs `x y z` variants when using mithril, I prefer not to introduce a third 😁 

I like `present` as I would prefer to have animation-related classes in Liminal. In fact, a `base` would be helpful too to put stuff like `transition transform` once and without having to think about where it should go.

**Comment by barneycarroll** [comment]
[I can't remember when I fixed this, but I did!](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvCLAB0oCcaACYAGSYkxQAvpzBtKWTgHIsEGgAs20ALRYM5eQJjKalSlDhSAOmhOwuzNvHpcAvKIwGYnEyaz4slAK60AFABNKci8cWnwAI0p-AE8SbhNOTgA3CBgAd0ROXwBKTlsAPk5kBMTOLF8pfDoADxplchsYNikSEtKyivCvGl00Fvi0dvaamgBhajpaTKkAFUoAc3nYFrah6nIoCHIAaxzgVaHOS2taPM4AQmO4GwPSoVbBoaFsh9vyqXDml9dH9uQrmycABkQNuiXKfFkgji+1+h044Qw12mNDYGDQcDkEGonH8XjRNGxaGUAHYAAxkzio9FwMDsLDKebMLycdgQeYCeqNZoPeGlGxsaLTSjMdRyaLKSlwciObQARgArGSVnDDjBqnJhaLyOLJZxpbLJSq+fcwaV3vI5fgBJs0NpwlAgtt+lIABIwKCO85SbJm32qzgAXV5pW+j0DJmeIDI11g5EJ1AQiBAACYyYgUySQEJgyBbdsk6gQJgcHhZAolFAiKQQPioHh5D1mHBEAB6Vs+Zjbeb4KhYVvlxTQAACKfwZPwABYB3Ih1XiNGQDRosxcMnpUpmDRsyR0Ng10uMNA0gJ-B4BL24DW6w2my3253u72JK2aEeoCe0P5yFfR-grSmrb+BAcA0K+76fmeUKXjWy6rngoHRLA2aBkIQA)
